turtle = nil
dofile('../ale/turtle/turtle.lua')

function Assert(booltest)
  if not booltest then
    error("Test failed")
  end
end


t = Turtle:new(1,1,1, "South")
Assert(t.position:compare({x = 1, y = 1, z = 1, face = 2}))
t:printPosition()
t:save_position("start")
print(t.saved_positions.start:toString())
t:goToPosition({x = 0, y = 0, z = 0, face = 0})
print("Located: "..t.position:toString())
print("Saved: "..t.saved_positions.start:toString())
t:save_position("end")
t:rewindToSavedPosition("start")
t:printPosition()
Assert(t.position:compare({x = 1, y = 1, z = 1, face = 2}))
t:replay(2)
t:replayToSavedPosition("end")
Assert(t.position:compare({x = 0, y = 0, z = 0, face = 0}))

t:forward()
Assert(t.position:compare(Position:new(0, 0, -1, 0)))
t:back()
Assert(t.position:compare(Position:new(0, 0, 0, 0)))
t:turnRight()
Assert(t.position:compare(Position:new(0, 0, 0, 1)))
t:forward()
Assert(t.position:compare(Position:new(1, 0, 0, 1)))
t:turnRight()
Assert(t.position:compare(Position:new(1, 0, 0, 2)))
t:forward()
Assert(t.position:compare(Position:new(1, 0, 1, 2)))
t:up()
Assert(t.position:compare(Position:new(1, 1, 1, 2)))
t:rewind(4)
Assert(t.position:compare(Position:new(0, 0, 0, 1)))
t:turnAround()
Assert(t.position:compare(Position:new(0, 0, 0, 3)))
t:forward()
t:forward()
t:back()
t:back()
t:back()
t:down()
Assert(t.position:compare(Position:new(1, -1, 0, 3)))
Slot = t.inventory:getSlot("minecraft:dirt")
Slot:select()


